# Generated by Django 4.2.13 on 2024-06-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('criacao_dt', models.DateTimeField(auto_now_add=True)),
                ('entrega_dt', models.DateField()),
                ('finalizacao_dt', models.DateField(null=True)),
            ],
        ),
    ]
