# Generated by Django 4.2.11 on 2024-10-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['entrega_dt']},
        ),
        migrations.AlterField(
            model_name='todo',
            name='entrega_dt',
            field=models.DateField(verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
